# create User

POST  http://localhost:3000/user 
Content-Type: application/json

{
        "username": "demo4",
        "password": "demo4"
}
    
######update User
PUT http://localhost:3000/user/5 
Content-Type: application/json

{
    "username": "demo4_updated",
    "password": "newpassword"
}

### Delete User
DELETE http://localhost:3000/user/4